### PR TITLE
Switched IV vector to openssl and added a test to verify it works as before

### PR DESCRIPTION
**Pull request by NoMan2000**
Added a quick unit test to verify that everything works and updated it to only use openssl.

### CODE REVIEW

**Comment by cstanke** [comment]
Great PR! Thanks. I hope this gets merged into master, otherwise I'll keep using NoMan2000's fork.

**Review by nickion — CHANGES_REQUESTED** [review]
Thanks for the pull request. The change is good, however for consistency and quality, please make a change to follow the same convention for the Exception message as with the others.

**Comment by dianjuar** [comment]
### This is a great PR!
#### I can use this PR on my php7.1 because `mcrypt` [has been deprecated](http://php.net/manual/en/migration71.deprecated.php) on php7.1

@nickion could you please suggest how the messages need to look like?
Is a shame that this super awesome PR can not be accepted for a simple message style

**Review by nickion — APPROVED** [review]

**Comment by bfentiman** [comment]
Thanks for the pull request, sorry it took us a while to merge it

**Pull request merged**
